### ISSUE TITLE
 Update v1.1.3 not blocking updates

### ISSUE THREAD

**Issue by MichaelBTryin** [kinsi55/BeatSaber_UpdateSkipper#10]
Hello, Am I the only one, or is this update not working?

Thanks

Michael

**Comment by kinsi55** [comment]
Just as the message after applying says, some times Steam will still show that there is an update, but clicking on the update button shouldn't do anything assuming you've done everything correctly

**Comment by kinsi55** [comment]
Actually, seems like I might have made a mistake in that update, I've released a new one that should fix it. Its confusing me tho because it still worked fine for many people. Let me know if that fixes it for you

**Comment by MichaelBTryin** [comment]
I'm still getting the update :( Well, perhaps its just me. thanks for trying tho.

**Comment by MichaelBTryin** [comment]
Oh, I deleted my app manifest and tried to launch it, it updated, but its still in 1.12.1. all seems good :) Thanks!
